version: '3'

services:
  node-app:
    image: node-back
    ports:
      - "${SERVER_PORT:-3333}:3333"
    environment:
      - SERVER_PORT=${SERVER_PORT:-3333}
      - DATABASE_URL=${DATABASE_URL:-mongodb://localhost:27017/mydatabase}
      - SALT_ROUNDS=${SALT_ROUNDS:-7}
      - SECRET=${SECRET:-mysecret}
      - TOKEN_VALIDITY=${TOKEN_VALIDITY:-5000}
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      - MONGO_PORT=${MONGO_PORT:-27017}

  vue-app:
    image: node-front
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_API_URL=http://node-app:3333
    depends_on:
      - node-app